version: "2.4"
services:
    osrm:
        container_name: osrm
        image: osrm/osrm-backend
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ../vroom-west/:/data
        command: "osrm-routed --max-matching-size 10000 --max-table-size 10000  --max-viaroute-size 10000 --algorithm mld /data/us-west-latest.osrm"
        networks:
            tsp_network:
                aliases:
                - osrm
    vroom-backend:
        container_name: vroom-backend
        image: vroomvrp/vroom-docker:v1.13.0
        volumes:
            - ./vroom-conf/:/conf
        environment:
            - VROOM_ROUTER=osrm
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - osrm
        networks:
            tsp_network:
                aliases:
                - vroom-backend
    vroom-frontend:
        container_name: vroom-frontend
        image: knightblood/vroom-frontend:latest
        restart: always
        ports:
            - 8050:9966
        depends_on:
            - osrm
            - vroom-backend
        networks:
            tsp_network:
                aliases:
                - vroom-frontend
networks:
  tsp_network:
      driver: bridge
